name: gtalcs

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ThirteenAG/WidescreenFixesPack/.github/workflows/all.yml@master
    with:
      tag_list: gtalcs
      project: /t:GTALCS_PCSX2_WidescreenFix
