name: gtavcs

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ThirteenAG/WidescreenFixesPack/.github/workflows/all.yml@master
    with:
      tag_list: gtavcs
      project: /t:GTAVCS_PCSX2_WidescreenFix
