name: scdaps2

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ThirteenAG/WidescreenFixesPack/.github/workflows/all.yml@master
    with:
      tag_list: scdaps2
      project: /t:SplinterCellDoubleAgent_PCSX2_WidescreenFix
