name: Release By Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: The tag of the release
        required: true
        type: choice
        options:
        - bully
        - burnout3
        - callofcthulhu
        - coldfear
        - condemned
        - da4
        - driv3r
        - driverpl
        - enterthematrix
        - farcry
        - fireteambravo1
        - fireteambravo2
        - fireteambravo3
        - gta1
        - gta2
        - gta3
        - gta3de
        - gtactwpsp
        - gtalcs
        - gtalcspsp
        - gtasa
        - gtasade
        - gtavc
        - gtavcde
        - gtavcs
        - gtavcspsp
        - gun
        - hd2
        - justcause
        - kingkong
        - kr
        - kr2
        - larush
        - mafia
        - mafiaxbox
        - manhunt
        - mp1
        - mp2
        - nfsc
        - nfsmw
        - nfsps
        - nfsu
        - nfsu2
        - nfsuc
        - onimusha3
        - paradisecracked
        - psiops
        - psychonauts
        - punisher
        - rdr
        - re0
        - re1
        - re2re3gc
        - re4
        - re5
        - re6
        - rerev
        - rerev2
        - sc
        - scarface
        - scc
        - scb
        - scct
        - scda
        - scdaps2
        - scdaxbox
        - sce
        - scpt
        - secondsight
        - sh2
        - sh3
        - sh4
        - sniperelite
        - sonicheroes
        - spyro
        - srs
        - thaw
        - thegodfather
        - thematrixpathofneo
        - thesaboteur
        - thesuffering
        - thewarriors
        - thps2
        - thps3
        - thps4
        - thug
        - thug2
        - tod
        - truecrimenyc
        - truecrimesola
        - xrd
        - usm

env:
  bully: "/t:Win32\\Bully_WidescreenFix"
  burnout3: "/t:PCSX2F\\Burnout3_PCSX2F_WidescreenFix"
  callofcthulhu: "/t:Win32\\CallOfCthulhu_WidescreenFix"
  coldfear: "/t:Win32\\ColdFear_WidescreenFix"
  condemned: "/t:Win32\\Condemned_WidescreenFix"
  da4: "/t:Win32\\DeerAvenger4_WidescreenFix"
  driv3r: "/t:Win32\\Driv3r_WidescreenFix"
  driverpl: "/t:Win32\\DriverParallelLines_WidescreenFix"
  enterthematrix: "/t:Win32\\EnterTheMatrix_WidescreenFix"
  farcry: "/t:Win32\\FarCry_WidescreenFix"
  fireteambravo1: "/t:PPSSPP\\SOCOM\\SOCOM_FireteamBravo_PPSSPP_FusionMod"
  fireteambravo2: "/t:PPSSPP\\SOCOM\\SOCOM_FireteamBravo2_PPSSPP_FusionMod"
  fireteambravo3: "/t:PPSSPP\\SOCOM\\SOCOM_FireteamBravo3_PPSSPP_FusionMod"
  gta1: "/t:Win32\\GrandTheftAuto\\GTA1_WidescreenFix"
  gta2: "/t:Win32\\GrandTheftAuto\\GTA2_WidescreenFix"
  gta3: "/t:Win32\\GrandTheftAuto\\GTA3_WidescreenFix"
  gta3de: "/t:Win64\\GrandTheftAuto\\GTA3DE_FusionMod"
  gtactwpsp: "/t:PPSSPP\\GrandTheftAuto\\GTACTW_PPSSPP_FusionMod"
  gtalcs: "/t:PCSX2F\\GrandTheftAuto\\GTALCS_PCSX2F_WidescreenFix"
  gtalcspsp: "/t:PPSSPP\\GrandTheftAuto\\GTALCS_PPSSPP_WidescreenFix /t:PPSSPP\\GrandTheftAuto\\GTALCS_PPSSPP_Project2DFX /t:PPSSPP\\GrandTheftAuto\\GTALCS_PPSSPP_ImVehLM"
  gtasa: "/t:Win32\\GrandTheftAuto\\GTASA_WidescreenFix"
  gtasade: "/t:Win64\\GrandTheftAuto\\GTASADE_FusionMod"
  gtavc: "/t:Win32\\GrandTheftAuto\\GTAVC_WidescreenFix"
  gtavcde: "/t:Win64\\GrandTheftAuto\\GTAVCDE_FusionMod"
  gtavcs: "/t:PCSX2F\\GrandTheftAuto\\GTAVCS_PCSX2F_WidescreenFix /t:PCSX2F\\GrandTheftAuto\\GTAVCS_PCSX2F_Project2DFX /t:PCSX2F\\GrandTheftAuto\\GTAVCS_PCSX2F_ImVehLM"
  gtavcspsp: "/t:PPSSPP\\GrandTheftAuto\\GTAVCS_PPSSPP_WidescreenFix /t:PPSSPP\\GrandTheftAuto\\GTAVCS_PPSSPP_Project2DFX /t:PPSSPP\\GrandTheftAuto\\GTAVCS_PPSSPP_ImVehLM /t:PPSSPP\\GrandTheftAuto\\GTAVCS_PPSSPP_GamepadIcons"
  gun: "/t:Win32\\Gun_WidescreenFix"
  hd2: "/t:Win32\\HiddenandDangerous2_WidescreenFix"
  justcause: "/t:Win32\\JustCause_WidescreenFix"
  kingkong: "/t:Win32\\KingKong_WidescreenFix"
  kr: "/t:Win32\\KnightRider_WidescreenFix /t:PCSX2F\\KnightRider_PCSX2F_WidescreenFix"
  kr2: "/t:Win32\\KnightRider2_WidescreenFix"
  larush: "/t:Win32\\LARush_WidescreenFix"
  mafia: "/t:Win32\\Mafia_WidescreenFix"
  mafiaxbox: "/t:CXBXR\\Mafia_CXBXR_WidescreenFix"
  manhunt: "/t:Win32\\Manhunt_WidescreenFix"
  mp1: "/t:Win32\\MaxPayne\\MaxPayne_WidescreenFix"
  mp2: "/t:Win32\\MaxPayne\\MaxPayne2_WidescreenFix"
  nfsc: "/t:Win32\\NeedForSpeed\\NFSCarbon_WidescreenFix"
  nfsmw: "/t:Win32\\NeedForSpeed\\NFSMostWanted_WidescreenFix"
  nfsps: "/t:Win32\\NeedForSpeed\\NFSProStreet_GenericFix"
  nfsu: "/t:Win32\\NeedForSpeed\\NFSUnderground_WidescreenFix"
  nfsu2: "/t:Win32\\NeedForSpeed\\NFSUnderground2_WidescreenFix"
  nfsuc: "/t:Win32\\NeedForSpeed\\NFSUndercover_GenericFix"
  onimusha3: "/t:Win32\\Onimusha3_WidescreenFix"
  paradisecracked: "/t:Win32\\ParadiseCracked_WidescreenFix"
  psiops: "/t:Win32\\PsiOpsTheMindgateConspiracy_WidescreenFix"
  psychonauts: "/t:Win32\\Psychonauts_WidescreenFix"
  punisher: "/t:Win32\\ThePunisher_WidescreenFix"
  rdr: "/t:Win64\\RedDeadRedemption_FusionMod"
  re0: "/t:Win32\\ResidentEvil\\ResidentEvil0_FusionFix"
  re1: "/t:Win32\\ResidentEvil\\ResidentEvil_FusionFix"
  re2re3gc: "/t:Dolphin\\ResidentEvil2_RE3_Dolphin_FusionMod"
  re4: "/t:Win32\\ResidentEvil\\ResidentEvil4_FusionMod"
  re5: "/t:Win32\\ResidentEvil\\ResidentEvil5_FusionFix"
  re6: "/t:Win32\\ResidentEvil\\ResidentEvil6_FusionFix"
  rerev: "/t:Win32\\ResidentEvil\\ResidentEvilRevelations_FusionFix"
  rerev2: "/t:Win32\\ResidentEvil\\ResidentEvilRevelations2_FusionFix"
  sc: "/t:Win32\\SplinterCell\\SplinterCell_WidescreenFix"
  scarface: "/t:Win32\\Scarface_FusionFix"
  scc: "/t:Win32\\SplinterCell\\SplinterCellConviction_FusionMod"
  scb: "/t:Win32\\SplinterCell\\SplinterCellBlacklist_FusionMod"
  scct: "/t:Win32\\SplinterCell\\SplinterCellChaosTheory_WidescreenFix"
  scda: "/t:Win32\\SplinterCell\\SplinterCellDoubleAgent_WidescreenFix"
  scdaps2: "/t:PCSX2F\\SplinterCellDoubleAgent_PCSX2F_WidescreenFix"
  scdaxbox: "/t:CXBXR\\SplinterCellDoubleAgent_CXBXR_WidescreenFix"
  sce: "/t:PPSSPP\\SplinterCellEssentials_PPSSPP_FusionMod"
  scpt: "/t:Win32\\SplinterCell\\SplinterCellPandoraTomorrow_WidescreenFix"
  secondsight: "/t:Win32\\SecondSight_WidescreenFix"
  sh2: "/t:Win32\\SilentHill\\SilentHill2_WidescreenFix"
  sh3: "/t:Win32\\SilentHill\\SilentHill3_WidescreenFix"
  sh4: "/t:Win32\\SilentHill\\SilentHill4_WidescreenFix"
  sniperelite: "/t:Win32\\SniperElite_WidescreenFix"
  sonicheroes: "/t:Win32\\SonicHeroes_WidescreenFix"
  spyro: "/t:Win64\\SpyroReignitedTrilogy_WidescreenFix"
  srs: "/t:Win32\\StreetRacingSyndicate_WidescreenFix"
  thaw: "/t:Win32\\TonyHawks\\TonyHawksAmericanWasteland_WidescreenFix"
  thegodfather: "/t:Win32\\TheGodfather_WidescreenFix"
  thematrixpathofneo: "/t:Win32\\TheMatrixPathOfNeo_WidescreenFix"
  thesaboteur: "/t:Win32\\TheSaboteur_FusionFix"
  thesuffering: "/t:Win32\\TheSuffering_WidescreenFix"
  thewarriors: "/t:PPSSPP\\TheWarriors_PPSSPP_FusionMod"
  thps2: "/t:Win32\\TonyHawks\\TonyHawksProSkater2_WidescreenFix"
  thps3: "/t:Win32\\TonyHawks\\TonyHawksProSkater3_WidescreenFix"
  thps4: "/t:Win32\\TonyHawks\\TonyHawksProSkater4_WidescreenFix"
  thug: "/t:Win32\\TonyHawks\\TonyHawksUnderground_WidescreenFix"
  thug2: "/t:Win32\\TonyHawks\\TonyHawksUnderground2_WidescreenFix"
  tod: "/t:Win32\\TotalOverdose_WidescreenFix"
  truecrimenyc: "/t:Win32\\TrueCrimeNewYorkCity_WidescreenFix /t:PCSX2F\\TrueCrimeNewYorkCity_PCSX2F_WidescreenFix"
  truecrimesola: "/t:Win32\\TrueCrimeStreetsofLA_WidescreenFix"
  xrd: "/t:PPSSPP\\PPSSPP_XboxRainDroplets /t:PCSX2F\\PCSX2F_XboxRainDroplets"
  usm: "/t:Win32\\UltimateSpiderMan_WidescreenFix"

jobs:
  setup_project_name:
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.prj_name.outputs.project_name }}
    steps:
      - name: Print inputs passed to the reusable workflow
        id: prj_name
        run: |
          echo "project_name=${{ env[inputs.tag_name] }}" >> $GITHUB_OUTPUT
  call-workflow-passing-data:
    needs: setup_project_name
    uses: ThirteenAG/WidescreenFixesPack/.github/workflows/all.yml@master
    with:
      tag_list: ${{ inputs.tag_name }}
      project: ${{ needs.setup_project_name.outputs.project_name }}
